repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
      - id: ruff
        name: ruff-isort
        args: [--select, I, --fix]
